### ISSUE TITLE
Having trouble getting it running on a raspberry pi

### ISSUE THREAD

**Issue by KraigM** [Parrot-Developers/node-flower-bridge#1]
I keep getting an issue when Im trying to startup the bridge (from one of the dependencies).  Its acting like it didn't compile or something.  I've tried it with and without sudo and rebuilding as well as a whole bunch of other things I've tried but no luck.  Any idea what I'm missing?

sudo ./bridge display

-- Flower Bridge --

module.js:485
  process.dlopen(filename, module.exports);
          ^
Error: /home/pi/node-flower-bridge/node_modules/flower-power-ble/node_modules/noble-device/node_modules/noble/node_modules/bluetooth-hci-socket/build/Release/binding.node: undefined symbol: node_module_register
    at Object.Module._extensions..node (module.js:485:11)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/home/pi/node-flower-bridge/node_modules/flower-power-ble/node_modules/noble-device/node_modules/noble/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)

**Comment by KraigM** [comment]
nvm.  It looks like it was an issue where I couldn't run as sudo but I had to make some changes to run without sudo (https://github.com/sandeepmistry/noble#running-on-linux).
